version: '3.8'
services:
  mysqldb:
    #platform: linux/amd64
    image: mysql:latest
    #container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservation
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  reservation-app:
    #build: .
    image: openjdk:26-jdk-trixie
    container_name: reservation-app
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/reservation?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
